export const VALIDATION_CHECK = {
  INVALIDATION_PASSWORD: 'INVALIDATION_PASSWORD',
  DIFFERENT_PASSWORD: 'DIFFERENT_PASSWORD',
  EMPTY_NAME: 'EMPTY_NAME',
  EMPTY_ID: 'EMPTY_ID',
  EMPTY_PASSWORD: 'EMPTY_PASSWORD',
  SUCCESS: 'SUCCESS'
}